// Generated by CoffeeScript 1.8.0
(function() {
  var GoogleSpreadsheet, sheet;

  GoogleSpreadsheet = require("google-spreadsheet");

  sheet = new GoogleSpreadsheet(process.env.SPREADSHEET_KEY);

  sheet.setAuth(process.env.GOOGLE_USER, process.env.GOOGLE_PASS, function(err) {
    var Validator, app, express, moment, validateForm, validators;
    if (err) {
      console.error(err);
      return process.exit(1);
    } else {
      express = require('express');
      moment = require('moment');
      Validator = require('validate-form');
      validators = {
        truthy: require('validate-form/truthy'),
        email: require('validate-form/email')
      };
      validateForm = Validator({
        name: [validators.truthy()],
        email: [validators.truthy(), validators.email("Please ensure that you enter valid email")],
        phone: [],
        company: [],
        position: [],
        message: []
      });
      app = express();
      app.enable('trust proxy');
      app.use(require('body-parser').urlencoded({
        extended: true,
        limit: '4kb',
        parameterLimit: 20
      }));
      app.post('/form', function(req, res) {
        var now, row, validationErrors;
        validationErrors = validateForm(req.body);
        if (validationErrors) {
          return res.send("validation failed");
        } else {
          row = req.body;
          now = moment();
          row.date = now.format('DD.MM.YYYY');
          row.time = now.format('HH:mm:ss');
          row.ip = req.ip;
          sheet.addRow(process.env.SPREADSHEET_SHEET_INDEX, row);
          return res.send('ok');
        }
      });
      return app.listen(process.env.PORT || 3000);
    }
  });

}).call(this);
